[package]
authors = ["Igor Pashev <pashev.igor@gmail.com>"]
license = "WTFPL"
name = "frotate"
version = "0.1.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
docopt = "1"
serde = { version = "1", features = ["derive"] }
